# Generated by Django 3.1.6 on 2021-04-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
