# Generated by Django 3.2 on 2021-08-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0002_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='created_by',
        ),
    ]
