# Generated by Django 3.1.5 on 2021-02-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0002_company_inspection_schedule_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='institution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
