# Generated by Django 3.2 on 2021-08-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0003_rename_user_blog_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_by',
            new_name='user',
        ),
    ]
