# Generated by Django 3.1.5 on 2021-02-03 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0003_schedule_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='name',
            new_name='type',
        ),
    ]
