# Generated by Django 3.1.5 on 2021-02-03 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0004_auto_20210203_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='inspection',
        ),
        migrations.AddField(
            model_name='inspection',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yonghun.company'),
        ),
    ]
