# Generated by Django 3.1.6 on 2021-04-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0005_auto_20210423_1603'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
