# Generated by Django 3.1.5 on 2021-02-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0005_auto_20210203_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yonghun.schedule'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yonghun.system'),
        ),
    ]
