# Generated by Django 3.1.6 on 2021-02-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0007_auto_20210203_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
