# Generated by Django 3.1.6 on 2021-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0011_auto_20210423_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
