# Generated by Django 3.1.6 on 2021-04-23 07:58

from django.db import migrations, models
import yonghun.models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0012_auto_20210423_1651'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', yonghun.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
