# Generated by Django 3.1.6 on 2021-04-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0013_auto_20210423_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
