# Generated by Django 3.1.6 on 2021-03-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0017_auto_20210308_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='updated_by',
        ),
    ]
