# Generated by Django 3.1.6 on 2021-03-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghun', '0019_auto_20210308_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
